Change genres and tags identifiers to integers
ProtocolONE/qilin.api pull request #16
Opened 2019-02-15 15:55 UTC by sundagy

2019-02-15 18:11 UTC, shersh requested changes

2019-02-15 18:11 UTC, shersh commented on pkg/api/game/dto.go
> +		Main        int          `json:"main"`
У нас ниже у Additional поля int64 а тут int32. Почему так?)

2019-02-15 18:11 UTC, shersh commented on pkg/orm/game_service.go
> +			return NewServiceError(http.StatusConflict, "Invalid genre")
Тут не конфликт, а 422, потому что нам передеали неверные валидные данные

2019-02-15 18:11 UTC, shersh commented on pkg/orm/game_service.go
> +			return NewServiceError(http.StatusConflict, "Invalid tag")
Тут тоже самое про 422

2019-02-15 18:11 UTC, shersh commented
Coverage упал аж на 5% =( Надо вернуть

2019-02-18 10:14 UTC, sundagy commented on pkg/api/game/dto.go
> +		Main        int          `json:"main"`
Да, правильней будет тоже int64.

2019-02-18 10:14 UTC, sundagy commented on pkg/orm/game_service.go
> +			return NewServiceError(http.StatusConflict, "Invalid tag")
Сделал

2019-02-18 10:14 UTC, sundagy commented on pkg/orm/game_service.go
> +			return NewServiceError(http.StatusConflict, "Invalid genre")
Сделал

2019-02-18 10:19 UTC, sundagy commented
> Coverage упал аж на 5% =( Надо вернуть

Это странно, так как новых функций в модуль game_service я не добавлял( там чисто проверку жанров добавил при обновлении игры.

2019-02-18 10:21 UTC, shersh approved these changes

2019-02-18 11:27 UTC, merged