Specs for role management api QILIN-53
ProtocolONE/qilin.api pull request #22
Opened 2019-03-06 14:48 UTC by shersh

2019-03-26 16:27 UTC, misterion requested changes

2019-03-26 16:27 UTC, misterion commented on pkg/api/access_rights_test.go
> +			// 1. Создатель может выполнить действие
на английском пожалуйста

2019-03-26 16:27 UTC, misterion commented on pkg/api/admin_onboarding_router.go
> +	r = r.Group(group,"/vendors", &router)
не думаете, что стоит в r.Group добавить возможность 4м параметром передать права? У болшОго числа роутеров все методы принимают единый набор параметров.

2019-03-26 16:27 UTC, misterion commented on pkg/api/price_router.go
> +	r = r.Group(group,"/games/:id", &priceRouter)
```
r := &middleware.RbacGroup{}
r = r.Group(group,"/games/:id", &priceRouter)
```
не думали изменить на 
```
r := &middleware.RbacGroup{group, &priceRouter}
r = r.Group("/games/:id",  []string{"id", model.GameType, model.VendorDomain})
....
```
?

2019-03-26 16:27 UTC, misterion commented on pkg/api/middleware/rbac.go
> +package middleware
Очень не удачное generic имя пакета - давайте заменим на rbac_echo. Это в том числе поможет переименовать часть структур пакета RbacRouter->Router, а сам вызов rbac_echo.Router

2019-03-26 16:27 UTC, misterion commented on pkg/api/middleware/rbac.go
> +type QilinContext struct {
Не думали, что AppContext подходит несколько удачнее по сравнению с QilinContext?

2019-03-26 16:27 UTC, misterion commented on pkg/api/utils.go
> +	gameIdParam := ctx.Param("id")
Очень опасный, имхо, подход с тем, что идентификатор игры из пути извлекается по имени `Id`, а не `gameId`. Не думали об этом?

2019-03-26 16:27 UTC, misterion commented on pkg/api/utils.go
> +	vendorIdParam := ctx.Param("id")
Аналогично комментарию выще, не `id`, но `vendorId`

2019-03-26 16:27 UTC, misterion commented on pkg/api/middleware/rbac.go
> +				return err
Мне кажется чертовски странным, что тут, в контексте этого обработчика вы просто пробрасываете ощибки наружу. Тут должна быть запись в лог и возврат 500 от сервера или , что мне кажется корректнее, StatusForbidden.

2019-03-26 16:27 UTC, misterion commented on pkg/orm/membership_service.go
> +	service.enforcer.AddPolicy(rbac.Policy{Role: model.SuperAdmin, Domain: "vendor", ResourceType: model.GameListType, ResourceId: "skip", Action: "any", Effect: "allow"})
Для чего эти 2 политики у супер админа? Для того, чтобы игнорировать проверку по id игры?

2019-03-26 16:27 UTC, misterion commented on pkg/orm/membership_service.go
> +	if gorm.IsRecordNotFoundError(err) {
Тяжело читается, не думаете, что так лучше: 
```
if err != nil {
     if gorm.IsRecordNotFoundError(err) {
        	return nil, NewServiceErrorf(http.StatusNotFound, "User %s not found", userId) 
     }
     return nil, NewServiceError(http.StatusInternalServerError, errors.Wrapf(err, "Get info about userId `%s`", userId))
} 	
```

2019-03-26 16:27 UTC, misterion commented on pkg/orm/membership_service.go
> +				err = service.db.DB().Model(&model.Game{}).Where("id = ?", rest.UUID).First(&game).Error
давайте через сервис игры, без прямой работы с базой и "чужой" сущностью

2019-03-26 16:27 UTC, misterion commented on pkg/orm/membership_service.go
> +					//TODO: add new field to game object
Как на клиенте покажут иконку? Забыли?

2019-03-26 16:27 UTC, misterion commented on pkg/orm/membership_service.go
> +		for _, ele := range skipNames {
у вас есть вспомогательный метод contains, почему тут его не используете?

2019-03-26 16:27 UTC, misterion commented on pkg/orm/utils.go
> +func GetUserId(db *gorm.DB, id string) (string, error) {
Почему этот метод в утилитах вместо сервиса пользователя? Так же стоит переименовать в GetUserById

2019-03-26 16:27 UTC, misterion commented on pkg/orm/utils.go
> +func GetOwnerForGame(db *gorm.DB, gameId uuid.UUID) (string, error) {
Аналогичный вопрос - почему это не в сервисе игры?

2019-03-26 16:44 UTC, shersh commented on pkg/orm/utils.go
> +func GetUserId(db *gorm.DB, id string) (string, error) {
Это код пришел при добавлении Auth1 b использовался раньше для получения ID пользователя используя ExternalID. От последнего мы отказались и этот метод стал не нужен. Будет удален

2019-03-26 16:45 UTC, shersh commented on pkg/orm/utils.go
> +func GetOwnerForGame(db *gorm.DB, gameId uuid.UUID) (string, error) {
Этот код используется в QilinContext'e у которого есть зависимость на db. Так нам придется добавить туда две других зависимости - VendorService, GameService

2019-03-26 16:59 UTC, shersh commented on pkg/api/middleware/rbac.go
> +				return err
На самом деле это частный случай. router.GetOwner на самом деле уже возвращает нужную ошибку, которая будет и залогирована. Дело в том, что ошибок в данном случае может быть больше, например 404 если не существует вендора для этого контекста

2019-03-26 17:04 UTC, shersh commented on pkg/orm/membership_service.go
> +	service.enforcer.AddPolicy(rbac.Policy{Role: model.SuperAdmin, Domain: "vendor", ResourceType: model.GameListType, ResourceId: "skip", Action: "any", Effect: "allow"})
Супер админ наследует права админа. Админ некоторые политики может только читать. В то время как супер админ имеет права на запись в этих случаях. 
Одна из них лишняя.

2019-03-26 19:07 UTC, sundagy commented on pkg/api/membership_router.go
> +	return ctx.JSON(http.StatusOK, users)
А где маппинг в DTO структуру?

2019-03-26 19:07 UTC, sundagy commented on pkg/orm/utils.go
> +	err := db.Model(&model.Vendor{}).Where("id = ?", vendorId).First(&vendor).Error
Можно так еще
err := db.Where(&model.Vendor{ID: vendorId}).First(&vendor).Error

2019-03-27 17:09 UTC, shersh commented on pkg/api/price_router.go
> +	r = r.Group(group,"/games/:id", &priceRouter)
Думали, но так не получится. у RbacGroup больше полей

2019-03-27 17:30 UTC, shersh commented on pkg/api/membership_router.go
> +	return ctx.JSON(http.StatusOK, users)
А он тут не нужен. У нас сервис сразу возвращает DTO потому что нет работы с БД

2019-03-27 17:41 UTC, shersh commented on pkg/orm/membership_service.go
> +					//TODO: add new field to game object
Это пока не было решено как правильно реализовывать и оставили на тех долг.

2019-03-28 12:42 UTC, misterion approved these changes

2019-03-29 10:43 UTC, merged