Base package / bundle entries
ProtocolONE/qilin.api pull request #27
Opened 2019-03-22 03:06 UTC by sundagy

2019-03-27 15:35 UTC, shersh commented on pkg/orm/database.go
> +		&model.Package{},
Надо добавить в DeleteAllTable все эти таблицы еще.

2019-03-27 17:09 UTC, sundagy commented on pkg/orm/database.go
> +		&model.Package{},
Ага, в сл коммите добавил.

2019-04-10 13:19 UTC, shersh requested changes

2019-04-10 13:19 UTC, shersh commented on .gitignore
> +go.mod
А это точно сработает. Если мы не будем комитить go.mod то получится что на сборочной машине не сможет собираться проект если будут новые модули подключены. Разве нет?

2019-04-10 13:19 UTC, shersh commented on pkg/api/access_rights_test.go
> +		urlUnapproved := format(key.url,
Там ниже есть еще метод generateTestCases
в него надо добавить кейсы с урлами которые надо дергать чтобы проверить есть ли права у пользователя

2019-04-10 13:19 UTC, shersh commented on pkg/api/bundle_router.go
> +func mapStoreBundleDto(bundle *model.StoreBundle, lang string) (dto storeBundleDTO, err error) {
А почему не использовать Mapper.Map ?
Тут же все названия полей совпадают

2019-04-10 13:19 UTC, shersh commented on pkg/api/bundle_router_test.go
> +func (suite *BundleRouterTestSuite) TestGetBundleShouldReturnEmptyObject() {
Мало тестов же? Они не покрывают всего того что написано в роутере сейчас

2019-04-10 13:19 UTC, shersh commented on pkg/api/package_router.go
> +	packageGroup.POST("/products/add", router.AddProducts, nil)
Зачем здесь /add и /remove ? есть же методы POST и DELETЕ

2019-04-10 13:19 UTC, shersh commented on pkg/api/package_router.go
> +	packages, err := router.service.GetList(vendorId, query, sort, offset, limit)
А на фронте не будет показываться сколько страниц есть? Для этого же надо возвращать общее кол-во айтемов по критерию

2019-04-10 13:19 UTC, shersh commented on pkg/model/bundle.go
> +	// TODO: Calc from prices
Это потом будет дорабатываться? Есть ли уже задача на это чтобы не забыть?

2019-04-10 13:19 UTC, shersh commented on pkg/orm/bundle_service.go
> +	gameService, _ := NewGameService(db)
а почему мы тут создаем gameService а не используем уже созданный ранее и не прокидываем его сюда?

2019-04-10 13:19 UTC, shersh commented on pkg/orm/bundle_service.go
> +		err = p.db.Where("id in (?)", packages).Find(&pkgObjs).Error
А без указания Model(model.Package) он разве поймет где выполнять запрос? Мне казалось gorm так не умеет

2019-04-10 13:19 UTC, shersh commented on pkg/orm/bundle_service.go
> +	db.Commit()
Коммит есть, а роллбека нет. Выше где ошибка, лучше вызвать Rollback руками я думаю

2019-04-10 13:19 UTC, shersh commented on pkg/orm/bundle_service.go
> +	db.Commit()
db.Commit возвращает err насколько я помню и её стоит проверить

2019-04-10 13:19 UTC, shersh commented on pkg/orm/bundle_service_test.go
> +	bundle, err := suite.service.CreateStore(suite.vendorId, "Mega bundle", suite.packages)
Тестов тоже мало. Не проверяются ошибки. Не проверяется разные случаи параметров

2019-04-10 13:19 UTC, shersh commented on pkg/orm/membership_service.go
> +	service.enforcer.AddPolicy(rbac.Policy{Role: model.Support, Domain: "vendor", ResourceType: model.PackageType, ResourceId: "*", Action: "read", Effect: "allow"})
Надо уточнить у @misterion может ли саппорт читать бандлы и пакеты. 
Вообще тут надо создать отдельную роль, которая уже имеет доступ к этому, по моему это было у Developer

2019-04-10 13:19 UTC, shersh commented on pkg/orm/package_service.go
> +	db.Commit()
тут стоит проверить .Error у Commit 
и выше добавить Rollback при ошибке

2019-04-10 13:19 UTC, shersh commented on pkg/orm/package_service.go
> +	batchDb.Commit()
Аналогично. Проверить .Error у commit

2019-04-10 13:19 UTC, shersh commented on pkg/orm/package_service_test.go
> +func (suite *packageServiceTestSuite) TestCreatePackage() {
Мало тестов. Некоторые методы вообще не покрыты (Remove, Update)

2019-04-11 09:20 UTC, sundagy commented on .gitignore
> +go.mod
Да верно, верну.

2019-04-11 10:12 UTC, sundagy commented on pkg/api/bundle_router.go
> +func mapStoreBundleDto(bundle *model.StoreBundle, lang string) (dto storeBundleDTO, err error) {
Мне как бы непонятны плюсы динамического маппинга кроме короткой интерпретации, там же если с одной стороны поменяется структура маппер об этом ничего не скажет и приведет к сложно выявляемой ошибке, разве не так?

2019-04-11 10:46 UTC, sundagy commented on pkg/api/bundle_router_test.go
> +func (suite *BundleRouterTestSuite) TestGetBundleShouldReturnEmptyObject() {
Да, сейчас расширю.

2019-04-11 10:47 UTC, sundagy commented on pkg/api/package_router.go
> +	packageGroup.POST("/products/add", router.AddProducts, nil)
в DELETE нельзя передавать тело запроса, а там целый список из uuid.

2019-04-11 12:11 UTC, shersh commented on pkg/api/package_router.go
> +	packageGroup.POST("/products/add", router.AddProducts, nil)
Ну вообще можно, просто не приветствуется 
https://tools.ietf.org/html/rfc7231#section-4.3.5

2019-04-12 10:13 UTC, sundagy commented on pkg/api/package_router.go
> +	packageGroup.POST("/products/add", router.AddProducts, nil)
Ну раз не приветствуется значит не надо использовать. Сваггер к тому же тело в DELETE воспринимает за ошибку.

2019-04-15 13:37 UTC, misterion requested changes

2019-04-15 13:37 UTC, misterion commented on pkg/model/bundle.go
> +		BuyOption       string
BuyOption  это enum, не строка

2019-04-15 13:37 UTC, misterion commented on docker-compose.yaml
> +      - ./etc/init.sql:/docker-entrypoint-initdb.d/init.sql
Миграция, которую требует PG должна начинаться с номеров. Зачем вы переименовали файл?

2019-04-15 13:37 UTC, misterion commented on pkg/api/bundle_router.go
> +func mapStoreBundleItemDto(bundle *model.StoreBundle) (dto storeBundleItemDTO) {
почему возврат по значению? вы же фактически копию возвращете, вместо объекта на стеке.

2019-04-15 13:37 UTC, misterion commented on pkg/api/package_router.go
> +			Image: p.GetImage(lang),
Мне кажется это странным. Зачем в этих операциях выносить логику на сервер и заморачиваться с языками? Возвращайте на клиент всегда все языки, что есть - логика того как ими пользоваться и что откуда читать будет реализована на клиенте. @shersh что думаешь? Я за то, чтобы убрать вообще фильтрацию по языкам в этом сервере.

2019-04-15 13:37 UTC, misterion commented on pkg/api/package_router.go
> +	dto, err := mapPackageDto(pkg, lang)
см. выше комментарий про филтрацию по языку.

2019-04-15 13:37 UTC, misterion commented on pkg/api/package_router.go
> +	pkg, err := router.service.Create(vendorId, params.Name, params.Products)
не понимаю, почему тут на вход отдельно принимают имя, отдельно продукты? Пакет имхо проще создавать отдельно - сначала только пакет, потом его наполнение.

2019-04-15 13:37 UTC, misterion commented on pkg/api/package_router.go
> +	pgk = model.Package{
Покажите где валидация вложенных структур - в Discount, DiscountBuyOpt, AllowedCountries я кажется могу передать что угодно.

2019-04-15 13:37 UTC, misterion commented on pkg/orm/package_service.go
> +func (p *PackageService) AddProducts(packageId uuid.UUID, prods []uuid.UUID) (result *model.Package, err error) {
Нет никаких проверок на права при записи продуктов - что передам то и вставиться. Могу создать пакет с продуктами лоюбых вендоров в не зависимости от того есть у меня на них права или нет.

2019-04-15 13:37 UTC, misterion commented on pkg/orm/package_service.go
> +				//...
wtf???

2019-04-15 13:37 UTC, misterion commented on .gitignore
@sundagy  у вас в IDE gofmt настроен? Я местами вижу куски кода, где он не выполнялся.

2019-04-15 13:37 UTC, misterion commented on pkg/api/game_router.go
> +		DefPackageID uuid.UUID  `json:"defPackageId"`
Не экономьте пожалуйста - DefaultPackageID

2019-04-15 13:37 UTC, misterion commented on pkg/model/bundle.go
> +	Bundle interface {
У package не хватает информации о том, что он дефолтный.

2019-04-15 13:37 UTC, misterion commented on pkg/model/bundle.go
> +	// TODO: Calc from prices
1. Это должно быть реализовано.
2. Не бывает цены - float. Цена это всегда структура с как минимум 2 полямя - currency (строковый код валюты), amount (числовое значение)

2019-04-15 13:37 UTC, misterion commented on pkg/model/game.go
> +		DefPackageID uuid.UUID
DefaultPackageID

2019-04-15 13:37 UTC, misterion commented on pkg/model/game.go
> +	found, _ := p.Media.CoverImage[lang]
Писал выше - лошгика у вас не верная что выше, что тут - если выбранного языка нет, берется язык по умолчанию (английский). Но это клиентская логика, не серверая имхо.

2019-04-15 13:37 UTC, misterion commented on pkg/model/package.go
> +		Name                string
Следующие 4 поля долдны быть локализуемы (имя и изображения)

2019-04-15 13:37 UTC, misterion commented on pkg/orm/bundle_service.go
> +	pkgObjs := []model.Package{}
полностью отсутсвует проверка прав - я могу создать бандл с любыми играми, даже теми к которым у меня нет доступа.

2019-04-15 13:37 UTC, misterion commented on pkg/orm/game_service.go
> +	item.DefPackageID = uuid.NewV4()
Очень странная логика - может выйти так, что я игру сохраню, но не смогу сохранить package.

2019-04-15 13:37 UTC, misterion commented on pkg/orm/package_service.go
> +	exist := &model.Package{Model: model.Model{ID: packageId}}
Я без проблем могу удалить пакет по умолчанию!!!

2019-04-15 13:37 UTC, misterion commented on pkg/orm/package_service.go
> +	return p.Get(pkg.ID)
не понятно зачем вы делаете запрос к БД когда у вас pkg уже под рукой

2019-04-15 13:37 UTC, misterion commented on spec/dashboard/games_openapi.yaml
> +  /api/v1/vendors/{vendorId}/packages/{id}/prices/{currency}:
выглядит так, что клиент вы сломали - правок клиентсой части при переносе цены в новое место не вижу в реквесте.

2019-04-15 14:20 UTC, pashakbit commented on spec/dashboard/games_openapi.yaml
> +  /api/v1/vendors/{vendorId}/packages/{id}/prices/{currency}:
Тут возможно стоит оставить обратную совместимость, а когда клиент переедет, то убрать лишнее

2019-04-16 12:23 UTC, sundagy commented on pkg/orm/membership_service.go
> +	service.enforcer.AddPolicy(rbac.Policy{Role: model.Support, Domain: "vendor", ResourceType: model.PackageType, ResourceId: "*", Action: "read", Effect: "allow"})
А почему бы суппорту не читать Бандлы и Пакеты?

2019-04-16 12:56 UTC, sundagy commented on pkg/orm/package_service.go
> +	db.Commit()
Сделал

2019-04-16 21:44 UTC, sundagy commented on pkg/orm/package_service_test.go
> +func (suite *packageServiceTestSuite) TestCreatePackage() {
Тесты расширил

2019-04-16 23:45 UTC, sundagy commented on pkg/orm/bundle_service_test.go
> +	bundle, err := suite.service.CreateStore(suite.vendorId, "Mega bundle", suite.packages)
Добавил новые проверки, проверку ошибок и параметров.

2019-04-16 23:51 UTC, sundagy commented on pkg/orm/package_service.go
> +	batchDb.Commit()
Сдеално

2019-04-17 01:42 UTC, sundagy commented on pkg/model/bundle.go
> +		BuyOption       string
Сделал enum.

2019-04-17 02:45 UTC, sundagy commented on pkg/api/bundle_router.go
> +func mapStoreBundleItemDto(bundle *model.StoreBundle) (dto storeBundleItemDTO) {
Тут и в остальных местах добавил ссылки.

2019-04-17 03:16 UTC, sundagy commented on docker-compose.yaml
> +      - ./etc/init.sql:/docker-entrypoint-initdb.d/init.sql
Там под виндой были проблемы с запуском докера при чтении этого файла и по совету из стека приходилось каждый раз его переименовывать, что в итоге привело его к такому названию. Сейчас та проблема ушла, имя вернул.

2019-04-17 05:32 UTC, sundagy commented on pkg/api/package_router.go
> +			Image: p.GetImage(lang),
В конкретно этом случае мы отдаем пакет и список включенных в него продуктов, их изображения ссылаются на обложки игр (поле Image). В апи пакетов мы можем менять его состав, но НЕ свойства самого продукта, для этого есть отдельное апи.

Из этого следует, что на фронте редактирования пакета не будет механизма смены обложек продуктов с переключением языка, для этого есть др раздел (/games/media).

По этому я посчитал оверхедом отдавать обложки продуктов на всех языках а отправлять  только на том на котором пользователь апи сам посчитает нужным.

2019-04-19 21:25 UTC, sundagy commented on pkg/orm/bundle_service.go
> +	pkgObjs := []model.Package{}
Проверку прав добавил в роутере для продуктов и пакетов.

2019-04-19 21:26 UTC, sundagy commented on pkg/orm/game_service.go
> +	item.DefPackageID = uuid.NewV4()
Объединил в создание игры и пакета по умолчанию в одну транзакцию

2019-04-19 22:54 UTC, sundagy commented on pkg/orm/package_service.go
> +	exist := &model.Package{Model: model.Model{ID: packageId}}
Добавил ограничение

2019-04-20 01:56 UTC, sundagy commented on pkg/orm/package_service.go
> +	return p.Get(pkg.ID)
Имеется ввиду, что на вход можно отправить модель без продуктов (для этого есть отдельные методы) а на выходе будем уметь полноценный пакет с полным набором игр и допов.

2019-04-20 03:04 UTC, sundagy commented on spec/dashboard/games_openapi.yaml
> +  /api/v1/vendors/{vendorId}/packages/{id}/prices/{currency}:
Сделал обратную совместимость.

2019-04-26 10:51 UTC, misterion requested changes

2019-04-26 10:51 UTC, misterion commented on pkg/api/game_router.go
> +		DefPackageID uuid.UUID  `json:"defPackageId"`
@sundagy up

2019-04-26 10:51 UTC, misterion commented on pkg/api/package_router.go
> +	packages, err := router.service.GetList(vendorId, query, sort, offset, limit)
@sundagy up

2019-04-26 10:51 UTC, misterion commented on pkg/model/bundle.go
> +	Bundle interface {
@sundagy up

2019-04-26 10:51 UTC, misterion commented on pkg/model/bundle.go
> +	// TODO: Calc from prices
@sundagy up

2019-04-26 10:51 UTC, misterion commented on pkg/model/game.go
> +		DefPackageID uuid.UUID
@sundagy up

2019-04-26 10:51 UTC, misterion commented on pkg/model/package.go
> +		Name                string
@sundagy up

2019-04-26 12:19 UTC, sundagy commented on .gitignore
Я использую jetbrains goland и там подсветки по правилам gofmt нет, по этому просто применил эту тулзу.

2019-04-26 14:22 UTC, sundagy commented on pkg/api/game_router.go
> +		DefPackageID uuid.UUID  `json:"defPackageId"`
поменял

2019-04-26 15:38 UTC, sundagy commented on pkg/api/package_router.go
> +	packages, err := router.service.GetList(vendorId, query, sort, offset, limit)
добавил X-Items-Count в заголовок

2019-04-29 02:42 UTC, sundagy commented on pkg/model/bundle.go
> +	Bundle interface {
добавил

2019-04-29 07:39 UTC, sundagy commented on pkg/model/bundle.go
> +	// TODO: Calc from prices
Сделал подсчет цены бандла, однако этот метод сейчас у нас нигде не используется.

2019-04-29 07:40 UTC, sundagy commented on pkg/model/game.go
> +		DefPackageID uuid.UUID
Переименовал

2019-04-29 08:13 UTC, sundagy commented on pkg/model/package.go
> +		Name                string
Сделал

2019-04-29 14:18 UTC, shersh commented on pkg/api/bundle_router.go
> +	bundleGroup := rbac_echo.Group(group, "/bundles", router, []string{"bundleId", model.RoleBundle, model.VendorDomain})
А нам тут точно не нужен /vendors/:vendorId в пути?

2019-04-29 14:18 UTC, shersh commented on pkg/api/bundle_router.go
> +		return echo.NewHTTPError(http.StatusUnprocessableEntity, "Wrong parameters in body")
Тут возвращается HttpError
а чуть ниже ServiceError
давайте приходить к одному типу ошибки. Я во всех сервисах и роутерах использую только ServiceError чтобы не было путаницы и был ожидаемый результат всегда один

2019-04-29 14:18 UTC, shersh commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
А тут не надо проверять айтемы в списке на предмет того можно ли их показывать или нет?

2019-04-29 14:18 UTC, shersh commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
Давайте придем к виду, мы:
- либо всегда возвращаем измененное состояние
- либо возврращаем NoContent с нужным статусом.

2019-04-29 14:18 UTC, shersh commented on pkg/model/bundle.go
> +				games = append(games, *game)
Мне кажется или тут что-то не так с указателями? 
Если бы games был сразу типа []*ProductGameImpl{} это бы все упростило? 
Или games должен быть типа интерфейса, который ProductGameImpl реализует

2019-04-29 14:18 UTC, shersh commented on pkg/orm/bundle_service.go
> +	gameService, _ := NewGameService(db)
@sundagy тут кажется забыли про вопрос

2019-04-29 14:18 UTC, shersh commented on pkg/orm/package_service.go
> +				//...
@sundagy тут надо или оставить ошибку о том что оно не реализовано и будет только когда-то в будущем или вообще убрать этот else if

2019-04-29 14:30 UTC, shersh commented on pkg/orm/package_service.go
> +		Sku:       random.String(8, "123456789"),
@misterion тут наверное нужно твое мнение, у нас получается sku рандомный набор цифр сейчас (который может совпасть с другими) - это ок?

2019-04-29 14:34 UTC, misterion requested changes

2019-04-29 14:34 UTC, misterion commented on .gitignore
нет, но там есть автоматическое gofmt  перед комитом - которое стоит включить и никогда не выключать.

2019-04-29 14:34 UTC, misterion commented on pkg/api/access_rights_test.go
> +	uId := random.String(8, "123456789")
В чем смысл менять UUID на случайные цифры?

2019-04-29 14:34 UTC, misterion commented on pkg/api/bundle_router.go
> +	bundleGroup.POST("/:bundleId/add", router.AddPackages, nil)
```
bundleGroup.POST("/:bundleId/add", router.AddPackages, nil)
bundleGroup.POST("/:bundleId/remove", router.RemovePackages, nil)
```
Это не верная структура для REST - действие для вас определеяет тип операции. Тут конкртено POST/DELETE. В запросе нет ресурса над которым выполняют действие. Конкретно /:bundleId/packages

2019-04-29 14:34 UTC, misterion commented on pkg/api/game_router.go
> +		DefPackageID uuid.UUID  `json:"defPackageId"`
В структуре я все еще вижу DefPackageID

2019-04-29 14:34 UTC, misterion commented on pkg/api/bundle_router.go
> +	vendorRouter.POST("/bundles/store", router.CreateStore, nil)
А что такое store тут? тип бандла?

2019-04-29 14:34 UTC, misterion commented on pkg/api/bundle_router.go
> +
Зачем вы получаете userId вне функции checkRBAC? Ведь он нигде кроме неё не используется.

2019-04-29 14:34 UTC, misterion commented on pkg/api/context/context.go
> +func GetLang(ctx echo.Context) (lang string) {
Эта функция не используется - удалите её.

2019-04-29 14:34 UTC, misterion commented on pkg/api/package_router.go
> +	packageGroup.POST("/:packageId/products/remove", router.RemoveProducts, nil)
```
packageGroup.POST("/:packageId/products/add", router.AddProducts, nil)
packageGroup.POST("/:packageId/products/remove", router.RemoveProducts, nil)
```
Уже писал выше. Тут не должно быть add/remove - это не валидный rest роутинг.

2019-04-29 14:34 UTC, misterion commented on pkg/api/package_router.go
> +		Products                []productDTO                         `json:"products" validate:"dive"`
Я не вижу флага "IsDefault"

2019-04-29 14:34 UTC, misterion commented on Dockerfile
> +FROM golang:1.11.1-alpine AS builderRUN apk add bash ca-certificates gitWORKDIR /applicationENV GO111MODULE=onCOPY go.mod go.sum ./RUN go mod download# Copy all files in currend directiry
wtf?

2019-04-29 14:34 UTC, misterion commented on docker-compose.yaml
> +version: "3.6"services:  centrifugo:    image: centrifugo/centrifugo:latest    environment:      - CENTRIFUGO_SECRET=secret      - CENTRIFUGO_ADMIN_PASSWORD=admin      - CENTRIFUGO_ADMIN_SECR
wtf?

2019-04-29 14:34 UTC, misterion commented on pkg/model/bundle.go
> +		CreateStore(vendorId uuid.UUID, userId, name string, packages []uuid.UUID) (bundle *StoreBundle, err error)
Не понимаю, почему BundleService  работет с StoreBundle  вместо интерфейса. Объясните

2019-04-29 14:34 UTC, misterion commented on pkg/model/bundle.go
> +func (b *StoreBundle) findPrice(p *Package, currency string) (float32, error) {
Я снова напишу тоже самое - цена это стурктура со скалярнывм значением и типом валюты. Мне кажется чертовски странным что в каком то месты мы работает с этим не как с обьектами а как с числами. Т.е. например у

```
pkgPrice, err := b.findPrice(&p, currency)
		if err != nil {
			return "", 0, err
		}
		price += pkgPrice
```
Было бы  
```
pkgPrice, err := b.findPrice(&p, currency)
		if err != nil {
			return "", 0, err
		}
		price += pkgPrice.GetAmount()
```

2019-04-29 14:34 UTC, misterion commented on pkg/model/bundle.go
> +func (b *StoreBundle) GetPrice() (currency string, price float32, err error) {
Цена забавная вещь. У вас не позможет типичный кейс - полная цена + цена со скидкой. Как это сейчас реализовать?

2019-04-29 15:48 UTC, sundagy commented on pkg/orm/bundle_service.go
> +	gameService, _ := NewGameService(db)
Пользователю BundleService будет легче его создавать, только из-из этого.

2019-04-29 15:49 UTC, sundagy commented on pkg/orm/bundle_service.go
> +		err = p.db.Where("id in (?)", packages).Find(&pkgObjs).Error
Умеет

http://gorm.io/docs/query.html

2019-04-29 15:50 UTC, sundagy commented on pkg/orm/bundle_service.go
> +	db.Commit()
Уже исправлено, спасибо.

2019-04-30 09:33 UTC, sundagy commented on pkg/api/package_router.go
> +	pkg, err := router.service.Create(vendorId, params.Name, params.Products)
Как по мне, пакет без заполнения вообще не должен существовать, так как позже это может привести к семантичесским ошибкам на платформе. Например, его могут по ошибки активировать, купить и как рендер странички пустого пакета в магазине может повести себя в этом случае.

2019-04-30 13:12 UTC, sundagy commented on pkg/api/package_router.go
> +	pgk = model.Package{
Сделал валидацию

2019-04-30 15:55 UTC, sundagy commented on pkg/orm/package_service.go
> +func (p *PackageService) AddProducts(packageId uuid.UUID, prods []uuid.UUID) (result *model.Package, err error) {
В прошлых коммитах я добавил в роутер проверку на права к добавляемым продуктам.

2019-04-30 16:05 UTC, sundagy commented on pkg/orm/package_service.go
> +				//...
Да тут должна быть загруска DLC и пока я поставлю сюда 501 ошибку, так потом будет легче найти где нужно будет дореализовать это.

2019-04-30 16:08 UTC, sundagy commented on pkg/api/game_router.go
> +		DefPackageID uuid.UUID  `json:"defPackageId"`
Не знаю как было позавчера, сейчас его точно нет.

![image](https://user-images.githubusercontent.com/1112805/56976275-425c3780-6b7b-11e9-8d84-3be16ca5cfcd.png)

2019-04-30 16:12 UTC, sundagy commented on pkg/model/game.go
> +	found, _ := p.Media.CoverImage[lang]
Да верно, в прошлых коммитах это пофиксино.

2019-04-30 16:47 UTC, sundagy commented on pkg/api/bundle_router.go
> +	bundleGroup := rbac_echo.Group(group, "/bundles", router, []string{"bundleId", model.RoleBundle, model.VendorDomain})
Я сделал по аналогии с играми, у создания и листинга в пути присутствует /vendors/:vendorId

2019-04-30 16:50 UTC, sundagy commented on pkg/api/bundle_router.go
> +		return echo.NewHTTPError(http.StatusUnprocessableEntity, "Wrong parameters in body")
Согласен, сделал replace во всех файлах api.

2019-04-30 17:06 UTC, sundagy commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
@misterion Подскажи, нам нужно проверять права при чтении списка бандлов?

2019-04-30 17:09 UTC, sundagy commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
@pashakbit Как ты считаешь будет лучше?

2019-04-30 17:14 UTC, sundagy commented on pkg/model/bundle.go
> +				games = append(games, *game)
Да верно, добавил *

2019-04-30 17:34 UTC, sundagy commented on pkg/api/access_rights_test.go
> +	uId := random.String(8, "123456789")
У нас сменился формат идентификатора пользователя, теперь мы его получаем из authOne и и на сколько помню оно точно не uuid а больше похоже на какой-то хешь и в этом тесте решил поменять на что-то близкое к реальности.

2019-04-30 17:46 UTC, sundagy commented on pkg/api/bundle_router.go
> +	bundleGroup.POST("/:bundleId/add", router.AddPackages, nil)
Packages в url я добавлю. По поводу DELETE, я читал c delete не рекомендуется отправлять тело запроса, по крайней мере swagger у меня ругается ошибкой при указании requestBody в delete-запросе.

2019-04-30 17:47 UTC, sundagy commented on pkg/api/bundle_router.go
> +	vendorRouter.POST("/bundles/store", router.CreateStore, nil)
Да, тип бандла, потом будет bundles/lootbox

2019-04-30 17:53 UTC, sundagy commented on pkg/api/bundle_router.go
> +
Используется

![image](https://user-images.githubusercontent.com/1112805/56982193-6e7eb500-6b89-11e9-82e6-cf5338a5d9bb.png)

2019-04-30 17:56 UTC, sundagy commented on pkg/api/context/context.go
> +func GetLang(ctx echo.Context) (lang string) {
Удалил

2019-04-30 17:58 UTC, sundagy commented on pkg/api/package_router.go
> +		Products                []productDTO                         `json:"products" validate:"dive"`
Было добавлено вчера в сл коммите

2019-05-05 08:48 UTC, sundagy commented on Dockerfile
> +FROM golang:1.11.1-alpine AS builderRUN apk add bash ca-certificates gitWORKDIR /applicationENV GO111MODULE=onCOPY go.mod go.sum ./RUN go mod download# Copy all files in currend directiry
Похоже я напутал с форматом перевода строки, поменял на LF.

2019-05-05 08:52 UTC, sundagy commented on docker-compose.yaml
> +version: "3.6"services:  centrifugo:    image: centrifugo/centrifugo:latest    environment:      - CENTRIFUGO_SECRET=secret      - CENTRIFUGO_ADMIN_PASSWORD=admin      - CENTRIFUGO_ADMIN_SECR
...то же самое, вернул LF.

2019-05-05 14:12 UTC, sundagy commented on pkg/model/bundle.go
> +		CreateStore(vendorId uuid.UUID, userId, name string, packages []uuid.UUID) (bundle *StoreBundle, err error)
Пользователю метода уже из названия понятно, что будет создан бандл для магазина и далее будет использовать как бандл магазина. То есть пользователю в данном случае проще работать именно с моделью а не с интерфейсом.

2019-05-05 17:11 UTC, sundagy commented on pkg/model/bundle.go
> +func (b *StoreBundle) findPrice(p *Package, currency string) (float32, error) {
Ок, сделал.

2019-05-06 03:15 UTC, sundagy commented on pkg/model/bundle.go
> +func (b *StoreBundle) GetPrice() (currency string, price float32, err error) {
Ну можно возварщать две стоимости со скидкой и без, еще можно отдавать цену без скидки + вычисленный % скидки бандла и применять ее где понадобится хоть при рендере.

2019-05-06 03:17 UTC, sundagy commented on pkg/orm/bundle_service.go
> +	gameService, _ := NewGameService(db)
Переделал, чтобы использовался уже созданный.

2019-05-06 05:29 UTC, sundagy commented on pkg/model/bundle.go
> +		CreateStore(vendorId uuid.UUID, userId, name string, packages []uuid.UUID) (bundle *StoreBundle, err error)
Поменял на интерфейс Bundle

2019-05-06 05:30 UTC, sundagy commented on pkg/model/bundle.go
> +func (b *StoreBundle) GetPrice() (currency string, price float32, err error) {
Сделал второе, теперь GetPrice отдает цену без скидки, саму скидку и валюту.

2019-05-06 08:17 UTC, misterion commented on pkg/orm/package_service.go
> +		Sku:       random.String(8, "123456789"),
Нет, не ок конечно. SKU это уникальное значение - он не должен совпадать с уже заведенными в системе.

2019-05-06 08:30 UTC, misterion commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
нет, перечень игр в бандле будут показывать всем у кого есть доступ на просмотр бандла. Это, впрочем, не дает никаких прав на сам доступ к этим играм из списка. Точно так же, ты не сможешь потом добавить игру в бандл, если у тебя к ней нет доступа.

2019-05-06 09:46 UTC, pashakbit commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
На мой взгляд, более универсальным будет возврат сущности

2019-05-06 15:40 UTC, sundagy commented on pkg/api/access_rights_test.go
> +	uId := random.String(8, "123456789")
Вернул uuid

2019-05-06 15:41 UTC, sundagy commented on pkg/api/bundle_router.go
> +	bundleGroup.POST("/:bundleId/add", router.AddPackages, nil)
Поменял на POST/DELETE и :bundleId/packages

2019-05-06 15:42 UTC, sundagy commented on pkg/api/package_router.go
> +	packageGroup.POST("/:packageId/products/remove", router.RemoveProducts, nil)
убрал add/remove

2019-05-06 15:43 UTC, sundagy commented on pkg/orm/package_service.go
> +		Sku:       random.String(8, "123456789"),
Поменял на uuid.NewV4()

2019-05-06 15:50 UTC, sundagy commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
@misterion здесь имеется ввиду, нужно ли проверять каждый бандл на предмет доступа пользователя когда выводим их списком? хотя пожалуй уже очевидно что надо)

2019-05-08 11:04 UTC, misterion approved these changes

2019-05-08 11:06 UTC, shersh commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
@sundagy что решили?

2019-05-08 11:16 UTC, sundagy commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
Давай возвращать сохраненную сущность, это поможет в тех случаях когда сервер что-то исправил за поступившими данными.

2019-05-08 12:02 UTC, sundagy commented on pkg/api/bundle_router.go
> +	return ctx.JSON(http.StatusOK, "OK")
В общем в некоторых случаях нет смысла возвращать состояние, например при удалении или апдейте со строгой проверкой, когда сервер ничего не меняет. И конкретно тут я сделал NoContent.

2019-05-08 12:31 UTC, sundagy commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
@shersh по-хорошему, проверка списка должно проходить через в бд, чтобы не ломать пагинацию. Как думаешь такое реально организовать?

2019-05-15 04:20 UTC, sundagy commented on pkg/api/bundle_router.go
> +	total, bundles, err := router.service.GetStoreList(vendorId, query, sort, offset, limit)
Добавил пагинацию для пакетов и бандлов.

2019-05-15 10:00 UTC, merged